title: Joseph Carruth # your name (or website title) here
logo: "/images/headshotjrc.webp" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>

  <span>
    <img style="vertical-align: middle; width: 20px;" src="https://img.icons8.com/fluency/48/000000/github.png"/>
    <a href="https://github.com/josephcarruth" style="font-size: 0.9rem; color: #0369a1;">
      @josephcarruth
    </a>
  </span>
  <span style="margin-left: 10px;">
    <img style="vertical-align: middle; width: 20px;" src="https://img.icons8.com/fluency/48/000000/linkedin.png"/>
    <a href="https://www.linkedin.com/in/joseph-carruth/" style="font-size: 0.9rem; color: #0369a1;">
      @joseph-carruth
    </a>
  </span>
  <span style="margin-left: 10px;">
    <img style="vertical-align: middle; width: 20px;" src="https://img.icons8.com/color/48/000000/pdf.png"/>
    <a href="pdf/Joseph Carruth - Professional Resume.pdf" style="font-size: 0.9rem; color: #0369a1;">
      Resume.pdf
    </a>
  </span>
  
theme: jekyll-theme-minimal
