title: Joseph Carruth # your name (or website title) here
logo: "/images/headshotjrc.webp" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>

  <div>
              <img className="inline w-6"
                src="https://img.icons8.com/fluency/48/000000/github.png"/>
                <span className="pl-1">
                  <a
                    className="text-sm font-light text-sky-700"
                    href="https://github.com/josephcarruth"
                  >
                    @josephcarruth
                  </a>
                </span>
          </div>
              <div>
                <img
                  className="inline w-6"
                  src="https://img.icons8.com/fluency/48/000000/linkedin.png"
                />
                <span className="pl-1">
                  <a
                    className="text-sm font-light text-sky-700"
                    href="https://www.linkedin.com/in/joseph-carruth/"
                  >
                    @joseph-carruth
                  </a>
                </span>
              </div>
              <div>
                <img
                  className="inline w-6"
                  src="https://img.icons8.com/color/48/000000/pdf.png"
                />
                <span className="pl-1">
                  <a
                    className="text-sm font-light text-sky-700"
                    href="PDF/Joseph Carruth - Professional Resume.pdf"
                  >
                    Resume.pdf
                  </a>
                </span>
              </div>
            </div>
            <hr />
          </div>
  
theme: jekyll-theme-minimal
